### PR TITLE
add title and different favicons

### LINKED ISSUE #52: Add <title> tag and favicon
BLOCKED: Need Favicon from Heather

To help users identify and distinguish different tabs and for bookmarking:

- Add a `<title>Frequency Provider Dashboard</title>` or similar
- Add a favicon.  See: https://medium.com/swlh/are-you-using-svg-favicons-yet-a-guide-for-modern-browsers-836a6aace3df

### PR DESCRIPTION
**Pull request by claireolmstead**
closes #52 
Screenshot 2024-01-23 at 4 33 56 PM

### CODE REVIEW

**Comment by claireolmstead** [comment]
many of these changes were from running the linter. should probably add a check to not pass without the linter passing.

**Comment by rlaferla** [comment]
Please resolve merge conflicts.

**Review by rlaferla — CHANGES_REQUESTED** [review]
Please resolve merge conflicts.

**Review by rlaferla — APPROVED** [review]

**Comment by claireolmstead** [comment]
Due to blockers, going to merge this story in with open TODOs. TODOs to be resolved in #113

**Pull request merged**
